[package]
name = "rustplay"
version = "0.1.0"
authors = ["ryym <ryym.64@gmail.com>"]

[[bin]]
name = "rustplay"
doc = false

[dependencies]
reqwest = "0.8.1"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
open = "*"
urlencoding = "*"
error-chain = "*"
getopts = "*"
